/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'expiringSoon' : bigint,
  'expiredMembers' : bigint,
  'totalMembers' : bigint,
  'activeMembers' : bigint,
}
export interface Member {
  'id' : string,
  'feeAmount' : bigint,
  'expiryDate' : bigint,
  'joiningDate' : bigint,
  'fullName' : string,
  'planDuration' : bigint,
  'paymentDate' : bigint,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMember' : ActorMethod<[string], undefined>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMember' : ActorMethod<[string], Member>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateMember' : ActorMethod<[Member], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];