/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'feeAmount' : IDL.Nat,
  'expiryDate' : IDL.Int,
  'joiningDate' : IDL.Int,
  'fullName' : IDL.Text,
  'planDuration' : IDL.Nat,
  'paymentDate' : IDL.Int,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'expiringSoon' : IDL.Nat,
  'expiredMembers' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'activeMembers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateMember' : IDL.Func([Member], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'feeAmount' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'joiningDate' : IDL.Int,
    'fullName' : IDL.Text,
    'planDuration' : IDL.Nat,
    'paymentDate' : IDL.Int,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'expiringSoon' : IDL.Nat,
    'expiredMembers' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'activeMembers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateMember' : IDL.Func([Member], [], []),
  });
};

export const init = ({ IDL }) => { return []; };